### ISSUE TITLE
Doesn't work with latest forge

### ISSUE THREAD

**Issue by martindiv** [NotEnoughMods/NEM-VersionChecker#4] opened 2015-08-09 13:51 UTC
Forge version: 10.13.4.1492
Minecraft Version: 1.7.10

It appears the forge group has remade the mod list screen in the latest forge giving it sorting and searching capabilities. Your override of drawSlot() doesn't appear to be working and the mods don't have their color codes or the version information you are adding to the list.

(A recent changelog on FML says they are now stripping color codes from mod names but that isn't really relevant here since you are trying to override the list entry renderer.)

**Comment by Pyker** [comment] 2015-08-26 17:05
It's working fine for me. Could it be some other mod?

**Comment by martindiv** [comment] 2015-09-19 21:44
Sorry it took so long to get back. Life happens.

Turns out it's ttCore that's rewriting the entire mod list screen.

**Comment by Pyker** [comment] 2015-09-19 21:45
Duplicate of #3, closing.

**Closed as completed by Pyker** 2015-09-19 21:45 UTC
Labels: duplicate
